auctionApp
    .service('PropertyService', ['$http', function($http) {

        //var urlBase = 'http://api.nestoria.in/api?place_name=delhi&listing_type=buy&country=in&encoding=json&action=search_listings&pretty=1';
        var urlBase = 'http://api.nestoria.in/api?encoding=json&action=search_listings&pretty=1';

        this.getProperties = function(place_name, listing_type, country) {
            var fullUrl = urlBase;
            console.log(place_name ? "&place_name=" + place_name : "");
            fullUrl += (place_name ? "&place_name=" + place_name : "");
            fullUrl += (listing_type ? "&listing_type=" + listing_type : "");
            fullUrl += (country ? "&country=" + country : "");
            console.log(fullUrl);
            //return $http.get(fullUrl);
            return [{
                "auction_date": null,
                "bathroom_number": 3,
                "bedroom_number": 3,
                "car_spaces": null,
                "commission": 0,
                "construction_year": 0,
                "datasource_name": "Housing.com",
                "guid": "g1-TMtATMzADM0g",
                "img_height": 120,
                "img_url": "http://1.l.in.nestoria.nestimg.com/lis/0/6/4/f6de7807b5ece9520e703e9a6bdbc5c4698ba.2.jpg",
                "img_width": 160,
                "keywords": "Spot Verified, Brand New, Garden, Gated Community, Gym, Lift, Power Backup, Security",
                "latitude": 28.6604690551757812,
                "lister_name": "Unity Group",
                "lister_url": "http://rd.nestoria.in/rd?itype=2&l=UYe-NGiQPiRGRJCiZ&s=&url=2-ePz73aTBU4LVGFByDI484Ner8aIMqOqnn3O6u50s2qDdmu-cfN_G5rWpMAbDMkMOx5gArFu8WfTVqv1bC8CmCShhtgBV1U2AdFjBUFFyMub3w0CkT5bec1R3eqf8DDElkUDyvVYCzhf9Y3su8nnYU2t45RHXvtbQ5Pifk6xjDHCflyZxBjvUI24XRG8zaBXeUuSKXD_GS_Ke_nCBr9gow2DvkMqLYldOPJDXZeZJ9ouWlrbMcnUJov-_oPktVlICf_z6qVKKHSkxl_3F7B2QGROcCL8J0V0073C6uZFx523Qej7-dlEmQwYkFuSYXM6V0CVTrtBc13OIN2wKaUfC8JI-j_GlyuYzWX8OgWV4wPtPynr2OkazLJ5OsLdgqrFJ4sA2itJucwF2tF-SsdHlP0pxcg%3D%3D&v=2",
                "listing_type": "buy",
                "location_accuracy": 9,
                "longitude": 77.1958389282226562,
                "price": 35837552,
                "price_currency": "INR",
                "price_formatted": "3.58 crores INR",
                "price_high": 35837552,
                "price_low": 35837552,
                "price_type": "fixed",
                "property_type": "flat",
                "size": 2569,
                "size_type": "gross",
                "size_unit": "ft2",
                "summary": "The Amaryllis, a luxurious residential building by Unity Group offers you...",
                "thumb_height": 60,
                "thumb_url": "http://3.l.in.nestoria.nestimg.com/lis/0/6/4/f6de7807b5ece9520e703e9a6bdbc5c4698ba.1.jpg",
                "thumb_width": 60,
                "title": "3BHK The Amaryllis, New Rohtak Road, Karol Bagh, Delhi, National Ca...",
                "updated_in_days": 6.5,
                "updated_in_days_formatted": "this week"
            }, {
                "auction_date": null,
                "bathroom_number": 1,
                "bedroom_number": 2,
                "car_spaces": null,
                "commission": 0,
                "construction_year": 0,
                "datasource_name": "CommonFloor",
                "floor": 1,
                "guid": "g1-yN10jNxcDM5gjYwIzM1c",
                "img_height": 120,
                "img_url": "http://1.l.in.nestoria.nestimg.com/lis/f/8/b/7cfb97494b4a8a6df7d499e8e42d9646c744f.2.jpg",
                "img_width": 160,
                "keywords": "Spot Verified, Builder floor, Brand New",
                "lister_name": "Sanchit",
                "lister_url": "http://rd.nestoria.in/rd?itype=2&l=UZe.OHjRQjSHSKDjb&s=&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOqnn3O6u50s2qDdmu-cfN_G5rGpMAbDMkMOx5IFrFu8WfXVqv1bC8CmCShhtgBV1U2AdFjBUFFyM-n6zUykT5bec1B1eKj8DDElkUDyvVYCzhf9Y3su8nnYU2t45RHXvtbQ5Pifk6xjDn2QkyF0AyWeaQsQWB89ZkTEQfvNRCfQTfbOsyTX4NZ3nCG-ycqGbV9PJJ_We-ZE-5CTm7zNaGoZ5K__oLZ9UgRMLee08g2OUHEwnP3d8huQGFGQCKAI21x2ommq5ZVq5mCaKyjlMgwlUQpnQbLbRJvGyj5M3MVc0CyYMz0BIV3YspUjmra9k-UNU3sYxXRwkeFDgX7wZVWoa8ZPqZxipvFX4s4wlsJib0h4tAaAo5ChfR5jN0QUoSB1R41R4UPaX6OYPS_fB59D&v=2",
                "listing_type": "buy",
                "price": 1877000,
                "price_currency": "INR",
                "price_formatted": "18.77 lakhs INR",
                "price_high": 1877000,
                "price_low": 1877000,
                "price_type": "fixed",
                "property_type": "flat",
                "size": 441,
                "size_type": "gross",
                "size_unit": "ft2",
                "summary": "2Bhk Semi Furnished Builder Floor near by Uttam Nagar West Metro Station Delhi",
                "thumb_height": 60,
                "thumb_url": "http://3.l.in.nestoria.nestimg.com/lis/f/8/b/7cfb97494b4a8a6df7d499e8e42d9646c744f.1.jpg",
                "thumb_width": 60,
                "title": "2BHK RWA Uttam Nagar Block U, Solanki Rd, Sanjay Enclave, Delhi",
                "updated_in_days": 4.5,
                "updated_in_days_formatted": "this week"
            }, {
                "auction_date": null,
                "bathroom_number": 4,
                "bedroom_number": 3,
                "car_spaces": null,
                "commission": 0,
                "construction_year": 2014,
                "datasource_name": "Makaan.com",
                "guid": "g1-SM00jMwgzN2Y",
                "img_height": 120,
                "img_url": "http://1.l.in.nestoria.nestimg.com/lis/7/8/9/bf59c58ff503216768f6a211c29f717578260.2.jpg",
                "img_width": 160,
                "keywords": "Builder floor, Brand New, Car Parking, Security, Marble Flooring",
                "lister_name": "Rajesh Singh",
                "lister_url": "http://rd.nestoria.in/rd?itype=2&l=UZe.OHjRQjSHSKDjc&s=&url=2-ePz73aTBU4LVGFByDI484Ner8aIMqOqnn3O6u50s2qDdmu-cfN_G5rOpMAbDMkMOx50NrFu8WfTVqv1bC8CmCShgtgBV1U2AdFjBUFFyMezzwkKkT5becFV2d6T8DDElkUDyvVYCzhf9Y3su8nnYU2t45RHXvtbQ5Pifk6xjB32XlCF0AznUI24XRG8zaBXeUuSKXD_GS_6a8nCBr9gow2DvkMqLYldTJ5DdbuJE7pKWmrzEcnMLs_Gx9_4zGEoaNeD6rRjWCHFpiLzd_h-fH1PRBL1Ll1d-4W2qu5Js_XPdNDr_NlEiVhdyCrPMD5jExjQTksxfzW-SfyEWY0TT7ZQuweSy1uBBXXQOjWBwk-1PwmupKlK2Zo9fr8Vlp7NW8YQ3i50tcEZ3ugac4ojzL0k2YR4TvnMpHNcA_lHZW6DBIi_ZFthMRZcycHGiK0I7q9W0_AWfCIKZ7U28rQUH8Zfajrfd7w%3D%3D&v=2",
                "listing_type": "buy",
                "price": 88000000,
                "price_currency": "INR",
                "price_formatted": "8.8 crores INR",
                "price_high": 88000000,
                "price_low": 88000000,
                "price_type": "fixed",
                "property_type": "house",
                "size": 2925,
                "size_type": "gross",
                "size_unit": "ft2",
                "summary": "Semi Furnished Builder Floor Available With Reserved Car Parking, Freehold...",
                "thumb_height": 60,
                "thumb_url": "http://3.l.in.nestoria.nestimg.com/lis/7/8/9/bf59c58ff503216768f6a211c29f717578260.1.jpg",
                "thumb_width": 60,
                "title": "3BHK Defence Colony Delhi South",
                "updated_in_days": 8.5,
                "updated_in_days_formatted": "last week"
            }, {
                "auction_date": null,
                "bathroom_number": 1,
                "bedroom_number": 4,
                "car_spaces": null,
                "commission": 0,
                "construction_year": 2015,
                "datasource_name": "Sulekha",
                "floor": 3,
                "guid": "g1-SOz0zN0ITO4k",
                "img_height": 120,
                "img_url": "http://1.l.in.nestoria.nestimg.com/lis/e/1/9/5b49d13b96e2ad84c5b68ba95ec97d2df9c41.2.jpg",
                "img_width": 160,
                "keywords": "Brand New, Garden, Gym, Lift, Car Parking, Power Backup, Security, Club House",
                "lister_name": "Sundersingh",
                "lister_url": "http://rd.nestoria.in/rd?itype=2&l=WVePeXzhgziXiaTzt&s=&url=2-ePz73aTBU4LVGFByDI474Ner8aIMqOqnn3O6u50s2qDdmu-cfN_G5rGpMAbDMkMOx50NrFu8WfTVqv1bC8CmCShgtgBV1U2AdFjBUFFyMezzwkKkT5becFV2d6T8DDElkUDyvVYCzhf9Y3su8nnYU2t45RHXvtbQ5Pifk6xjCHeSlCF0AznUI24XRG8zaBXeUuSKXD_GS_WY93CBr9gow2DvkMqLYl9TIJLdb-RD7pWbl7vFf3MOs_Gx9_4zGEoaNeD6rRjWCHZskOLV7QCHUE6KC7dN0FI17mquudUu6m_eNCj4ME0jQREmQ7vGBo-HzD8TlcZVx2-IN3wHY1jZ8ZkI3eDiirJVDCUfnH1KjuZf3nzhdUm6eZ9Vr4Fi6aE%3D&v=2",
                "listing_type": "buy",
                "price": 72500000,
                "price_currency": "INR",
                "price_formatted": "7.25 crores INR",
                "price_high": 72500000,
                "price_low": 72500000,
                "price_type": "fixed",
                "property_type": "flat",
                "size": 2200,
                "size_type": "gross",
                "size_unit": "ft2",
                "summary": "Brand New Third Floor With Terrace Garden For Sale At South Extension-II...",
                "thumb_height": 60,
                "thumb_url": "http://3.l.in.nestoria.nestimg.com/lis/e/1/9/5b49d13b96e2ad84c5b68ba95ec97d2df9c41.1.jpg",
                "thumb_width": 60,
                "title": "4BHK Defence Colony, Delhi - Lift",
                "updated_in_days": 12.5,
                "updated_in_days_formatted": "last week"
            }, {
                "auction_date": null,
                "bathroom_number": 3,
                "bedroom_number": 3,
                "car_spaces": 1,
                "commission": 0,
                "construction_year": 0,
                "datasource_name": "IndiaProperty",
                "floor": 3,
                "guid": "g1-SNz0jN2IzMzI",
                "img_height": 120,
                "img_url": "http://1.l.in.nestoria.nestimg.com/lis/2/d/2/e7bf8dfc31c0c573579038acf468e4f473e71.2.jpg",
                "img_width": 160,
                "keywords": "Brand New, Garden, Gym, Lift, Power Backup, Security, Swimming Pool, Club House",
                "lister_name": "Propfinder India",
                "lister_url": "http://rd.nestoria.in/rd?itype=2&l=UZe.OHjRQjSHSKDje&s=&url=2-ePz73aTBU4LVGFByDI484Ner8aIMqOqnn3O6u50s2qDdmu-cfN_G5rGpMAbDMkMOx50NrFu8WfTVqv1bC8CmCShgtgBV1U2AdFjBUFFyMevxyEOkT5becFR_eaT8DDElkUDyvVYCzhf9Y3su8nnYU2t45RHXvtbQ5Pifk6xjC3WXlCF0AznUI24XRG8zaBXeUuSKXD_GSP-Y93CBr9gow2DvkMqLYlNTIJXcYeVB7pKWmr3Kc3INs_Gx9_4zGEoaNeD6rRjWCHFpiLzZ8RCXH02NCKJDykdio2as-84wpWXdcmfvLEgrQAZ5CLHFBpLYiDdRg45Aw22OfzgKIVjX9ZA2mvq-3-wNRjcOjXx9lKRI1TL0OkivbIJUuY1x5rVX58AwyZ92dwp3q0_Yv5OlfBxhPEIQ4S0oA95I8grZZaODJy_VA4BbSZp6Znq3JnQ5vYn0oU_GXpLath-TtA4RpYzSwLGa9HXcTX9PbRjmdW06Z15Jukbr4VWeEuWilClEEApN&v=2",
                "listing_type": "buy",
                "price": 40000000,
                "price_currency": "INR",
                "price_formatted": "4 crores INR",
                "price_high": 40000000,
                "price_low": 40000000,
                "price_type": "fixed",
                "property_type": "flat",
                "size": 1800,
                "size_type": "gross",
                "size_unit": "ft2",
                "summary": "Live the high life in the heart of the city Presenting the finest homes in...",
                "thumb_height": 60,
                "thumb_url": "http://3.l.in.nestoria.nestimg.com/lis/2/d/2/e7bf8dfc31c0c573579038acf468e4f473e71.1.jpg",
                "thumb_width": 60,
                "title": "3BHK Lajpat Nagar 3, Delhi - Gym",
                "updated_in_days": 8.5,
                "updated_in_days_formatted": "last week"
            }, {
                "auction_date": null,
                "bathroom_number": 2,
                "bedroom_number": 2,
                "car_spaces": null,
                "commission": 0,
                "construction_year": 2015,
                "datasource_name": "HDFC Red",
                "guid": "g1-TMtIjMxUjM=c",
                "img_height": 120,
                "img_url": "http://2.l.in.nestoria.nestimg.com/lis/f/a/7/038827f62d1765d29399419c193a14d855c99.2.jpg",
                "img_width": 160,
                "keywords": "Brand New, Gym, Security, Club House",
                "lister_name": "Mahalaxmi",
                "lister_url": "http://rd.nestoria.in/rd?itype=2&l=UWe8LEgONgPEPHAgc&s=&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOqnn3O6u50s2qDdmu-cfN_G5rOpMAbDMkMOx5gArFu8WfTVqv1bC8CmCShgtgBV1U2AdFjBUFFyMO_0yECkT5becFpyfaX8DDElkUDyvVYCzhf9Y3su8nnYU2t45RHXvtbQ5Pifk6xjCXeVkidxAyWeaQsQWB9saBXeWLzVXDTWVPKe8yXFqNdn3Hauxd-CeURSM9KWOvBK4c7W1v7GZWlM5qq96ug5WQJdObrtsk_WV2960qeFrEPBDFiZBL1C3Q516Ha3-ZNq6SHbdhX9NlEyVEF2&v=2",
                "listing_type": "buy",
                "price": 6226650,
                "price_currency": "INR",
                "price_formatted": "62.27 lakhs INR",
                "price_high": 6226650,
                "price_low": 6226650,
                "price_type": "fixed",
                "property_type": "flat",
                "size": "",
                "size_type": "gross",
                "size_unit": "",
                "summary": "Mahaluxmi Homz, a project by Mahaluxmi Group features amenities such as...",
                "thumb_height": 60,
                "thumb_url": "http://1.l.in.nestoria.nestimg.com/lis/f/a/7/038827f62d1765d29399419c193a14d855c99.1.jpg",
                "thumb_width": 60,
                "title": "2BHK Mahaluxmi Homz, Kaushambi, Ghaziabad, Delhi",
                "updated_in_days": 8.5,
                "updated_in_days_formatted": "last week"
            }, {
                "auction_date": null,
                "bathroom_number": 1,
                "bedroom_number": 2,
                "car_spaces": null,
                "commission": 0,
                "construction_year": 0,
                "datasource_name": "CommonFloor",
                "floor": 1,
                "guid": "g1-yN10jNxcDMjdGNmNzNxA",
                "img_height": 120,
                "img_url": "http://1.l.in.nestoria.nestimg.com/lis/f/8/b/7cfb97494b4a8a6df7d499e8e42d9646c744f.2.jpg",
                "img_width": 160,
                "keywords": "Spot Verified, Brand New",
                "lister_name": "Sanchit",
                "lister_url": "http://rd.nestoria.in/rd?itype=2&l=UWe8LEgONgPEPHAgd&s=&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOqnn3O6u50s2qDdmu-cfN_G5rGpMAbDMkMOx5IFrFu8WfTVqv1bC8CmCShhtgBV1U2AdFjBUFFyM-n6zUykT5bec1B1eKj8DDElkUDyvVYCzhf9Y3su8nnYU2t45RHXvtbQ5Pifk6xjDXWWnCF0AyWeaQsQWB89ZkTEQfvNRCfQTfbOsyTX4NZ3nCG-ycqGbV9PJJ_We-ZE-5CQkrzOaGoZ5K__oLZ9UgRMLee08g2OUHEwnP3d8huQGFGQCKAI21x2ommq5ZVq5mCaKyjlMgwlUQpnQbLbRJvGyj5M3MVc0CyYMz0BIV3YspUjmra9k-UNU3sYxXRwkeFDgX7wZVWoa8ZPqZxipvFX4s4wlsJib0h4tAaAo5ChfR5jOB5C8HZxQIlR4UPaX6OYPS_fB59D&v=2",
                "listing_type": "buy",
                "price": 2018000,
                "price_currency": "INR",
                "price_formatted": "20.18 lakhs INR",
                "price_high": 2018000,
                "price_low": 2018000,
                "price_type": "fixed",
                "property_type": "flat",
                "size": 441,
                "size_type": "gross",
                "size_unit": "ft2",
                "summary": "Semi Furnished 2BHK Builder Floo for Sale in RWA Uttam Nagar Block,Solanki...",
                "thumb_height": 60,
                "thumb_url": "http://3.l.in.nestoria.nestimg.com/lis/f/8/b/7cfb97494b4a8a6df7d499e8e42d9646c744f.1.jpg",
                "thumb_width": 60,
                "title": "2BHK RWA Uttam Nagar Block U, Solanki Rd, Sanjay Enclave, Delhi",
                "updated_in_days": 4.5,
                "updated_in_days_formatted": "this week"
            }, {
                "auction_date": null,
                "bathroom_number": 1,
                "bedroom_number": 1,
                "car_spaces": null,
                "commission": 0,
                "construction_year": 0,
                "datasource_name": "CommonFloor",
                "floor": 4,
                "guid": "g1-yN10WN0QjMkd2NiRTN4I",
                "img_height": 120,
                "img_url": "http://1.l.in.nestoria.nestimg.com/lis/d/0/a/db755742a53e5b6ee00c4ab804c43eb43d2b0.2.jpg",
                "img_width": 160,
                "keywords": "Spot Verified, Builder floor",
                "lister_name": "Vinod Shorey",
                "lister_url": "http://rd.nestoria.in/rd?itype=2&l=UWe8LEgONgPEPHAge&s=&url=2-ePz73aTBU4LVGFByDI4-4Ner8aIMqOqnn3O6u50s2qDemu-cfN_G5rGpMAbDMkMOx5IFrFu8WfTVqv1bC8CmCShhtgBV1U2AdFjBUFFyM-n6zUykT5bec1B1eKj8DDElkUDyvVYCzhfjdGUS9S6LHT5t7xDLrJaO67ez_8RjE2fUzWshETPadndrbEkjZkqBGe2MXD_GTuqe8CTHqsN423akxdmJdFFcPYWRJL5S-YTK1vqMOXwUvqrk9aI8VR1VMvrosU2WVSh9kP-f8x2NClSRAP0X2ltwoGe2_41n7XWYfybiNlNqQgx5CKTIBZiHzD8ThNdHw2zGPDADbUab-4U7hr7_i74IAChdjCdxn7wYlCDidUm6eZ9Vr4Fi6aE%3D&v=2",
                "listing_type": "buy",
                "price": 1700000,
                "price_currency": "INR",
                "price_formatted": "17 lakhs INR",
                "price_high": 1700000,
                "price_low": 1700000,
                "price_type": "fixed",
                "property_type": "flat",
                "size": 355,
                "size_type": "gross",
                "size_unit": "ft2",
                "summary": "A Semi Furnished 1BHK Builder Floor for Sale in Uttam Nagar, Delhi",
                "thumb_height": 60,
                "thumb_url": "http://3.l.in.nestoria.nestimg.com/lis/d/0/a/db755742a53e5b6ee00c4ab804c43eb43d2b0.1.jpg",
                "thumb_width": 60,
                "title": "1BHK Builder Floor Apartment, Uttam Nagar, Delhi",
                "updated_in_days": 4.5,
                "updated_in_days_formatted": "this week"
            }, {
                "auction_date": null,
                "bathroom_number": 1,
                "bedroom_number": 2,
                "car_spaces": null,
                "commission": 0,
                "construction_year": 0,
                "datasource_name": "CommonFloor",
                "floor": 3,
                "guid": "g1-yN10jNxcGM4UjZ4cDZ4A",
                "img_height": 120,
                "img_url": "http://2.l.in.nestoria.nestimg.com/lis/e/9/9/31598ef846661db2d703178cd39c412a79692.2.jpg",
                "img_width": 160,
                "keywords": "Spot Verified, Builder floor, Brand New",
                "lister_name": "Sanchit",
                "lister_url": "http://rd.nestoria.in/rd?itype=2&l=VbeLaTvdcveTeWPvu&s=&url=2-ePz73aTBU4LVGFByDI494Ner8aIMqOqnn3O6u50s2qDdmu-cfN_G5rGpMAbDMkMOx5IFrFu8WfTVqv1bC8CmCShhtgBV1U2AdFjBUFFyM-n6zUykT5bec1B1eKj8DDElkUDyvVYCzhf9Y3su8nnYU2t45RHXvtbQ5Pifk6xjDnySlSF0AyWeaQsQWB89ZkTEQfvNRCfQTfbOsyTX4NZ3nCG-ycqGbV9PJJ_We-ZE-5CTm7_OaGoZ5K__oLZ9UgRMLee08g2OUHEwnP3d8huQGFGQCKAI21x2ommq5ZVq5mCaKyjlMgwlUQpnQbLbRJvGyj5M3MVc0CyYMz0BIV3YspUjmra9k-UNU3sYxXRwkeFDgX7wZVWoa8ZPqZxipvFX4s4wlsA1NRAq707N6pKvLh9rMBtL_XU1BNcc7h-WRw%3D%3D&v=2",
                "listing_type": "buy",
                "price": 1951000,
                "price_currency": "INR",
                "price_formatted": "19.51 lakhs INR",
                "price_high": 1951000,
                "price_low": 1951000,
                "price_type": "fixed",
                "property_type": "flat",
                "size": 441,
                "size_type": "gross",
                "size_unit": "ft2",
                "summary": "2Bhk Semi Furnished Builder Floor near by Uttam Nagar West Metro Station Delhi",
                "thumb_height": 60,
                "thumb_url": "http://1.l.in.nestoria.nestimg.com/lis/e/9/9/31598ef846661db2d703178cd39c412a79692.1.jpg",
                "thumb_width": 60,
                "title": "2BHK RWA Uttam Nagar, Pankha Rd, JJ Colony, Delhi",
                "updated_in_days": 4.5,
                "updated_in_days_formatted": "this week"
            }, {
                "auction_date": null,
                "bathroom_number": 3,
                "bedroom_number": 3,
                "car_spaces": null,
                "commission": 0,
                "construction_year": 0,
                "datasource_name": "CommonFloor",
                "floor": 4,
                "guid": "g1-yN10WN0QzMlJTOmJGM2Q",
                "img_height": 120,
                "img_url": "http://1.l.in.nestoria.nestimg.com/lis/d/0/a/db755742a53e5b6ee00c4ab804c43eb43d2b0.2.jpg",
                "img_width": 160,
                "keywords": "Spot Verified, Builder floor, Brand New",
                "lister_name": "Vinod Shorey",
                "lister_url": "http://rd.nestoria.in/rd?itype=2&l=VceMbUwedwfUfXQwnm&s=&url=2-ePz73aTBU4LVGFByDI484Ner8aIMqOqnn3O6u50s2qDdmu-cfN_G5rGpMAbDMkMOx5IFrFu8WfTVqv1bC8CmCShhtgBV1U2AdFjBUFFyM-n6zUykT5bec1B1eKj8DDElkUDyvVYCzhf9Y3su8nnYU2t45RHXvtbQ5Pifk6xjC3SXlCF0AyWeaQsQWB89ZkTEQfvNRCfTSPfOsyTX4NZ3nCG-ycqGbVBJI5XTb_9E956Uk7bPfGQXs6jh7q5lGBhMKeT95w3WUHFp0fHf8hmREFuTCL1UllB04Cqv_5J34WnSNnnvMUpqRhZiSbPMG9DMyT5Rg45VzXPGITAIaRnf8c0imqOx06YCVX0Lmj1xmOVCxTCxfUPrOdlf5Npl-7gPvM9siopzd0hptkrX8Q%3D%3D&v=2",
                "listing_type": "buy",
                "price": 4100000,
                "price_currency": "INR",
                "price_formatted": "41 lakhs INR",
                "price_high": 4100000,
                "price_low": 4100000,
                "price_type": "fixed",
                "property_type": "flat",
                "size": 710,
                "size_type": "gross",
                "size_unit": "ft2",
                "summary": "A Semi Furnished 3BHK Builder Floor for Sale in residentail builder floor...",
                "thumb_height": 60,
                "thumb_url": "http://3.l.in.nestoria.nestimg.com/lis/d/0/a/db755742a53e5b6ee00c4ab804c43eb43d2b0.1.jpg",
                "thumb_width": 60,
                "title": "3BHK Builder Floor Apartment, Uttam Nagar, Delhi",
                "updated_in_days": 4.5,
                "updated_in_days_formatted": "this week"
            }, {
                "auction_date": null,
                "bathroom_number": 3,
                "bedroom_number": 3,
                "car_spaces": null,
                "commission": 0,
                "construction_year": 0,
                "datasource_name": "CommonFloor",
                "floor": 2,
                "guid": "g1-yN10WN0QzMlVjNwc2YwQ",
                "img_height": 120,
                "img_url": "http://1.l.in.nestoria.nestimg.com/lis/d/0/a/db755742a53e5b6ee00c4ab804c43eb43d2b0.2.jpg",
                "img_width": 160,
                "keywords": "Spot Verified, Builder floor, Brand New",
                "lister_name": "Vinod Shorey",
                "lister_url": "http://rd.nestoria.in/rd?itype=2&l=VXeHWPrZYraPaSLrii&s=&url=2-ePz73aTBU4LVGFByDI484Ner8aIMqOqnn3O6u50s2qDdmu-cfN_G5rGpMAbDMkMOx5IFrFu8WfTVqv1bC8CmCShhtgBV1U2AdFjBUFFyM-n6zUykT5bec1B1eKj8DDElkUDyvVYCzhf9Y3su8nnYU2t45RHXvtbQ5Pifk6xjC3SXlCF0AyWeaQsQWB89ZkTEQfvNRCfTSPfOsyTX4NZ3nCG-ycqGbVBJI5XTb_9E956Uk7bPfmQXs6jh7q5lGBhMKeT95w3WUHFp0fHf8hmREFuTCL1UllB04Cqv_5J34WnSNnnvMUpqRhZiSbPMG9DMyT5Rg45VzXPGITAIaRnf8c0imqOx06YCVX0Lmj1xmOVCxTCxfUPrOd5f698zqLgJvM9siopzd0hptkrX8Q%3D%3D&v=2",
                "listing_type": "buy",
                "price": 4100000,
                "price_currency": "INR",
                "price_formatted": "41 lakhs INR",
                "price_high": 4100000,
                "price_low": 4100000,
                "price_type": "fixed",
                "property_type": "flat",
                "size": 710,
                "size_type": "gross",
                "size_unit": "ft2",
                "summary": "A Semi Furnished 3BHK Builder Floorfor Sale in residentail builder floor...",
                "thumb_height": 60,
                "thumb_url": "http://3.l.in.nestoria.nestimg.com/lis/d/0/a/db755742a53e5b6ee00c4ab804c43eb43d2b0.1.jpg",
                "thumb_width": 60,
                "title": "3BHK Builder Floor Apartment, Uttam Nagar, Delhi",
                "updated_in_days": 4.5,
                "updated_in_days_formatted": "this week"
            }];
        };
    }]);
